### ISSUE TITLE
Aligned Point Clouds

### ISSUE THREAD

**Issue by pbonazzi** [Gorilla-Lab-SCUT/SCUTSurface-code#5]
Thank you for your amazing work !

Is there a file I can use with rotatation matrix to rotate the point clouds to the correct position ?
As an example `synthetic_object_GT/complex/aphrodite.ply` is upside down .

**Comment by Huang-ZhangJin** [comment]
Thanks for your interest.

In our benchmark, we have promised that the points clouds are aligned with the gt meshes.
Objects are not oriented in the same ways, since there are many categories in the benchmark.
If you want to rotate an object,  you might make sure the point cloud and the mesh are oriented in the same way.
Example code:
```
import numpy as np
import trimesh
import trimesh.transformations as tt

mesh_file = "aphrodite.ply"
pts_file = "aphrodite.txt"

mesh = trimesh.load(mesh_file)
pts = np.loadtxt(pts_file)
pts_vert = trimesh.PointCloud(vertices=pts[: , :3])
pts_norm = trimesh.PointCloud(vertices=pts[:, 3:])

# Reference to https://trimsh.org/trimesh.transformations.html
deg2rad = 180/np.pi
rxyz = tt.euler_matrix(90*deg2rad, 0*deg2rad, 0*deg2rad, "rxyz")

mesh.apply_transform(rxyz)
pts_vert.apply_transform(rxyz)
pts_norm.apply_transform(rxyz)

mesh.export(f"rot_{mesh_file}")
pts_rot = np.concatenate([pts_vert.vertices, pts_norm.vertices], axis=-1)
np.savetxt(f"rot_{pts_file}.txt", pts_rot, fmt='%.6f')
```
